### ISSUE TITLE
Cannot delete SMS message 

### ISSUE THREAD

**Issue by gj1118** [briankabiro/react-native-get-sms-android#11]
Hi, 
I am trying to delete a message. As you can see from the image below that I am using the Default SMS app as my messaging app. 

![image](https://user-images.githubusercontent.com/473101/38285240-501998b8-378d-11e8-85ee-2227811d24a9.png)

I am using this code to delete a SMS message that I had sent 10 minutes earlier. 

The error message that comes up points that **it cannot find it**, yet I can confirm that the SMS exists. I took the screenshot 
![screenshot_1522809665](https://user-images.githubusercontent.com/473101/38285892-5a225cfc-3790-11e8-88fb-6795973a108b.png)
 

```Javascript
	SmsAndroid.delete(smsObject._id, (fail) => {
	    Toast.show("Failed with this error: " + fail)
	    return false
	}, (success) => {
	    Toast.show("SMS deleted successfully");
	    return true
	});
```
I am using **Android 5.1.1**
Can you please help me out with this?  

Thanks and Regards
Gagan

**Comment by davidstoneham** [comment]
Have you implemented the correct permissions and handlers for the default SMS app? See here https://android-developers.googleblog.com/2013/10/getting-your-sms-apps-ready-for-kitkat.html

This plugin has not been successfully tested on deleting SMS on android 5 and higher yet so I won't be able to provide too much assistance. It should be a matter of making sure you have the correct handlers and receivers setup so the device gives you write access to delete the messages.

**Comment by gj1118** [comment]
@davidstoneham , thanks for replying back. I am not sure I quite understand . This is because I am just getting started with Android development. I apologize sincerely. 

I have made sure that the default app is the one handling the messages. Do I need to give it more permissions ?  Or do I need to give my app more permissions ?  If I have to give my app more permissions , then I have given my app , the necessary three permissions already. 

```xml
    <uses-permission android:name="android.permission.READ_SMS" />
    <uses-permission android:name="android.permission.WRITE_SMS" />
    <uses-permission android:name="android.permission.SEND_SMS" />
```

Can you please let me know what else I should be doing?  

thank you once again for your time and patience.
With Regards
Gagan

**Comment by davidstoneham** [comment]
@gj1118 you may need to implement the intent filters in the apps manifest file. I'm not 100% since I've never done this before. You'll need to find a guide to make a sms app on android >5 to work out what exactly you need in order to get Android to give you delete permission.

**Comment by mikehardy** [comment]
For android >5 the only app permitted to delete an SMS message is the app installed as the default SMS handler. If your app is not set as the default SMS handler it will not be able to delete, so I believe this result (delete failure) is expected as you have not set your app as the default sms handler

**Comment by briankabiro** [comment]
Hi @gj1118. Going to close this for now as it's inactive. Feel free to reopen it if the issue persists.

**Comment by VatsalManiya** [comment]
hii can you send me that default sms app project?
if it's on java.
