### ISSUE TITLE
Not able to Read SMS Broadcast Messages

### ISSUE THREAD

**Issue by ayushmankd** [briankabiro/react-native-get-sms-android#14]
It is able to read Messages from contacts but not from any sms broadcasters.

**Comment by briankabiro** [comment]
Hey. @ayushmankd. Apologies for the delay in replying to this. Any luck?

**Comment by ayushmankd** [comment]
@briankabiro Sorry, I am currently not working on the product for which this functionality was needed.

**Comment by briankabiro** [comment]
@ayushmankd. Going to close this for now as it's inactive.
