### ISSUE TITLE
Permission denied com.android.providers.telephony.SmsProvider

### ISSUE THREAD

**Issue by UnnikrishnanBhargavakurup** [briankabiro/react-native-get-sms-android#17]
I'm getting the following error:

Permission denied com.android.providers.telephony.SmsProvider

Please see the attached screenshot.

<img width="274" alt="screen shot 2018-10-08 at 6 19 08 pm" src="https://user-images.githubusercontent.com/825646/46610186-9ba14280-cb27-11e8-9961-38322eb6450c.png">

**Comment by davidstoneham** [comment]
This error means the app has not been given access to read the messages of the device. You can manually give it permission via the settings > apps > permissions on your device or use a plugin to request permission from the user. You'll also need to make sure you have the correct imports in your manifest file too (these are outlined in the readme)
