### ISSUE TITLE
Event listener Not Working

### ISSUE THREAD

**Issue by AnthonyMwangi** [briankabiro/react-native-get-sms-android#24]
Hi,
Can't seem to get the **_sms_onDelivery_** Event listener to work. I'm using a Huawei Mate 10 Lite running on Android 8.0.

Am I missing something?
Do you have snippets for any working implementation?

**Comment by briankabiro** [comment]
Hey @AnthonyMwangi. Are you seeing any error or nothing at all?

**Comment by AnthonyMwangi** [comment]
Nothing At all

**Comment by AnthonyMwangi** [comment]
Hey @briankabiro updated to **_version 1.3.7_** and it now works properly.
Thank You.

**Comment by briankabiro** [comment]
Great. Thanks for the patience 👍
