### ISSUE TITLE
error: incomparable types: boolean and <null>

### ISSUE THREAD

**Issue by amirito** [briankabiro/react-native-get-sms-android#25]
I just import this module into my project but I get this error when I want to build:

> error: incomparable types: boolean and <null>

**Comment by briankabiro** [comment]
Hi, apologies for this.
Going to fix this with this #26.

**Comment by briankabiro** [comment]
This should be fixed now with the new release 1.3.7. Could you confirm and let me know?

**Comment by mikehardy** [comment]
this is definitely working for me now

**Comment by briankabiro** [comment]
Thanks, @mikehardy. Think we can close this one then.
