### ISSUE TITLE
how to read the messages past week/month like that? i need to reed past 10/15days messages only...

### ISSUE THREAD

**Issue by logesssh** [briankabiro/react-native-get-sms-android#31]
@mikehardy @tapanprakasht @tvc97 @davidstoneham

**Comment by mikehardy** [comment]
Per the README, you can filter like so:
https://github.com/briankabiro/react-native-get-sms-android/blob/master/README.md#list-sms-messages

If those don't do what you like (filter by date range or similar) feel free to open a PR, but other than that I believe your immediate solution must involve pagination starting at 0, with reasonable page sizes, filtering in JS and stopping when you hit the end of your date range.
