### ISSUE TITLE
sender is like az-paytm,ixpaytm means how can we assign address field. in sms listener, they have like this sender.contains("paytm"). they will get all type of senders sms

### ISSUE THREAD

**Issue by logesssh** [briankabiro/react-native-get-sms-android#32]
@mikehardy @tapanprakasht @briankabiro

**Comment by mikehardy** [comment]
No version, no sample code showing the SMS json and what you tried. The docs show filtering

**Comment by logesssh** [comment]
I am asking how to filter all messages sent by paytm. Paytm have senders VM-IPAYTM, AXiPaytm, HPvpaytm, etc.. like that. I need to filter paytm messages but cant filter by senders because it will change in future by AM-paytm,VXpaytm,CPpaytm like that. is there any option in this package for this help me..

ex. **sms-listener-paackage**

let subscription = SmsListener.addListener(message => {
      let sender =message.originatingAddress
       if(sender.includes("paytm")){
          this.setState({
            messageBody : message.body,
          });
       subscription.remove();
      }
    })

here it shows all messages received by paytm. like that i am asking
