### ISSUE TITLE
Build is breaking in my app

### ISSUE THREAD

**Issue by vijayperlakota** [briankabiro/react-native-get-sms-android#4]
@briankabiro 

I have followed the steps listed but my app is not getting built.
Below are the logs:
:react-native-get-sms-android:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
/node_modules/react-native-get-sms-android/android/src/main/java/com/react/SmsPackage.java:28: error: method does not override or implement a method from a supertype
    @Override
    ^
1 error
:react-native-get-sms-android:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

My package.json snippet:

"dependencies": {
    "react": "16.0.0-alpha.12",
    "react-native": "0.48.2",
    "react-native-get-sms-android": "^1.3.2"
  },

Let me know am I missing anything? 

Do I need to use any other version of RN?

**Comment by briankabiro** [comment]
@vijayperlakota let me check it out and I'll get back to you

**Comment by vijayperlakota** [comment]
@briankabiro 
Thanks for your reply.

I tried `gradlew clean` still the issue persists.

My `java -version` is

java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)


Let me know is there a specific version of Java needs to be used.

Thanks,
-VJ

**Comment by davidstoneham** [comment]
Hey yep this is an issue with the newer version of react. I'll fix this up today and also add in an example app for testing and reference in the project

**Comment by davidstoneham** [comment]
@vijayperlakota This should now be fixed in the latest version

**Comment by vijayperlakota** [comment]
Thanks @davidstoneham
