### ISSUE TITLE
Sent messages don't show up

### ISSUE THREAD

**Issue by tahins** [briankabiro/react-native-get-sms-android#42]
Sent messages using `SmsAndroid.autoSend` method don't show up when I fetch messages (`SmsAndroid.list`) or from any other SMS app.

**Comment by briankabiro** [comment]
Hey @tahins. Are you using any parameters on `SmsAndroid.list`?

**Comment by tahins** [comment]
Yes. The only parameters I am using is this -

```
{
    box: ''
}
```
