### ISSUE TITLE
Automatic SMS Read (SOLVED)

### ISSUE THREAD

**Issue by UnluckyLAD** [briankabiro/react-native-get-sms-android#50]
Hi,

I am currently at a stage where my "read" SMS is fully functional and I'm able to get an ALERT to pop up with the body of an unread text message by pressing a button.

However, I would like the alert to show up  automatically whenever a new message comes in rather than having to press the button each time. Is that possible in any way? I thought about ComponentDidUpdate (not sure if that's appropriate) but I'm not sure on how to apply it.
 Any tips?

Here is the getSMS Function 

```
`  getSMS = () => {
    let filter = {
      box: 'inbox',
      read: null,
      id: null,
      address: null,
      body: 'JobID:',  
      indexFrom: 0, 
      maxCount: 10, 
    };
    SmsAndroid.list(
      JSON.stringify(filter),
      fail => {
        console.log('Failed with this error: ' + fail);
      },
      (count, smsList) => {
        console.log('Count: ', count);
        console.log('List: ', smsList);
        var arr = JSON.parse(smsList);

        arr.forEach(function(object) {
          console.log('Object: ' + object);
          console.log('-->' + object.date);
          console.log('-->' + object.body);

          alert('You Have a new job!: \n' + object.body);
        });
      },
    );
  };`
```

Please note the 'null' is only there for testing purposes, I will explain further below the render method. 

here is the render method: 
```
 render() {
    return (
      <React.Fragment>
      <CardView
        getSMS={this.getSMS}
      />
       </React.Fragment> 
    );
  }
}

```
EDIT:

SOLVED BY USING REACT NATIVE ANDROID SMS LISTENER LIBRARY.

**Comment by briankabiro** [comment]
Hey, @UnluckyLAD. Glad to see that you found a solution; sad to see that help didn't come from here. 😉
