### ISSUE TITLE
How can I programmatically update an SMS setting "read" status to true?

### ISSUE THREAD

**Issue by frabanca** [briankabiro/react-native-get-sms-android#54]
I've seen that each SMS has the following structure:
```
interface ISMS {
  _id: number;
  address: string; // Phone address
  announcements_subtyle: number;
  app_id: number;
  body: string;
  correlation_tag: string;
  creator: string;
  d_rpt_cnt: number;
  date: number;
  date_send: number;
  deletable: 0;
  error_code: number;
  favorite: number;
  hidden: number;
  locked: number;
  msg_id: number;
  pri: number;
  protocol: number;
  read: number;
  reply_path_present: number;
  reserved: number;
  roam_pending: number;
  safe_message: number;
  secret_mode: number;
  seen: number;
  service_center: string;
  sim_imsi: string;
  sim_slot: 0;
  spam_report: number;
  status: number;
  sub_id: number;
  acv_cmd: number;
  teleservice_id: number;
  thread_id: number;
  type: number;
  using_mode: number;
}
```

And I've seen that I can use 'read' filter while reading SMS messages from phone, but once I've read and handled a single SMS I'd like to update his 'read' status to true to avoid to re-reading it. 

How can it be done?

Thanks for any help!

**Comment by briankabiro** [comment]
Hey @frabanca; I don't think we have the functionality to update the values at the moment. 

A potential solution could be storing the `ids` of messages that the user has read on your end and maintaining your own read status. :)

**Comment by frabanca** [comment]
Hi @briankabiro ! Thanks for your quick reply! 

I'll go for that way! 👍 :)

**Comment by briankabiro** [comment]
Awesome; glad to be of help!

**Comment by mu-irshad011** [comment]
any update on this, @briankabiro ? Does this package have this functionality now?

Is there a way we can update status to true even if user opens default sms app, it should also update there?

Thanks for any help!
