### ISSUE TITLE
autoSend is not a function

### ISSUE THREAD

**Issue by andreatoso** [briankabiro/react-native-get-sms-android#6]
Hi, I just installed this module. It is linked correctly but when I try to send a SMS I get this error:
"_reactNativeGetSmsAndroid2.default.autoSend is not a function". Why I get this error?
This is my code: 
`import SmsAndroid  from 'react-native-get-sms-android';

const instructions = Platform.select({
  ios: 'Press Cmd+R to reload,\n' +
  'Cmd+D or shake for dev menu',
  android: 'Double tap R on your keyboard to reload,\n' +
  'Shake or press menu button for dev menu',
});

export default class App extends Component<{}> {
  
  sendsms = () => {
    SmsAndroid.autoSend("0966666622", "hello", (fail) => {
      console.log("Failed with this error: " + fail)
    }, (success) => {
      console.log("SMS sent successfully");
    });
  }
  
  render() {
    return (
      <View style={styles.container}>
        <Button title="Press" onPress={() => this.sendsms()}/>
      </View>
    );
  }
}
`

**Comment by davidstoneham** [comment]
Hi there. This looks like you're using an older version of the plugin. Make sure you've got the latest version installed.

**Comment by andreatoso** [comment]
I tried to update and these are my versions:
"react-native": "0.49.2",
"react-native-get-sms-android": "^1.3.2"
but it doesn't work. I tried to send,delete and list but I always get this error. Why?

**Comment by briankabiro** [comment]
@andreatoso I've updated the package on npm. It's now version 1.4.
@davidstoneham Good catch

**Comment by andreatoso** [comment]
@briankabiro It works like a charm, thank you for updating! You can close.
