### ISSUE TITLE
send msg to multiple numbers

### ISSUE THREAD

**Issue by AreebVohra** [briankabiro/react-native-get-sms-android#61]
i want to send msg to multiple numbers at once 
this is what i'm doing, but getting error "com.facebook.bridge.ReadableNativeArray cannot be cast to java.lang.String"

``` 
someFunction = () => {
    SmsAndroid.autoSend(
      ['03422114890', '03422114999'],
      'hello',
      (fail) => {
        alert(fail);
      },
      (success) => {
        alert(success);
      },
    );
  }
```

i also tried this
```
someFunction = async () => {
    var phoneNumber = {
      "addressList": ["123", "456"]
    }

    SmsAndroid.send(
      phoneNumber,
      'hello world',
      (fail) => {
        alert(fail);
      },
      (success) => {
        alert(success);
      },
    );
  }
```

**Comment by AreebVohra** [comment]
i'll be damned, it was so simple
why hasn't this been mentioned in the docs please add this to the README
```
var phoneNumber = {
          "addressList": ["123", "456", "789"]
        }

        SmsAndroid.send(
          JSON.stringify(phoneNumber),
          'hello world',
          (fail) => {
            alert(fail);
          },
          (success) => {
            alert(success);
          },
        );
```

**Comment by briankabiro** [comment]
Sorry about that, @AreebVohra. Glad to see that you found a solution. 

Let me open up a PR to update the README with the information. 🏃 🏃

**Comment by briankabiro** [comment]
Done and merged. 

Thanks again for including the code!

**Comment by AreebVohra** [comment]
> 
> 
> Done and merged.
> 
> Thanks again for including the code!

hello @briankabiro i tried your code that you added in the README it will not work because if you look in the android native code it requires a json object with key "addressList" 
i recommend you try running the and see the outcome

**Comment by briankabiro** [comment]
You are right, Areeb. 

It does expect the addressList key. I'll make sure that I test it out

**Comment by adefemi171** [comment]
@AreebVohra I keep getting `Failed with this error: Generic failure` using your example

```
    let numbers = {
      "addressList": ["+2349****", "+2348****"]
    };
```

```
const message = "Hey this is automated"

    SmsAndroid.autoSend(
      JSON.stringify(numbers),
      message,
      (fail) => {
        console.log('Failed with this error: ' + fail);
      },
      (success) => {
        alert(JSON.stringify('SMS sent successfully'))
        console.log('SMS sent successfully' + success);
      }
    )
```

**Comment by areebvohra** [comment]
@adefemi171 i have not used this package in a while
