### ISSUE TITLE
Reading MMS

### ISSUE THREAD

**Issue by offaxis** [briankabiro/react-native-get-sms-android#65]
Hi,
Is it possible to read MMS with this lib ?

Thanks

**Comment by briankabiro** [comment]
Hey, @offaxis 👋 

I haven't tried using MMS but it seems that we don't currently support it.  [MMS](https://developer.android.com/reference/android/provider/Telephony.Mms) uses `Telephony.Mms` and the package only loads `Telephony.SmsManager` in the code. 

Have you found a package that provides this functionality? If not, I think MMS should be something that this package supports.

**Comment by offaxis** [comment]
Thanks for your answer !

I create another library inspired of this : https://stackoverflow.com/questions/3012287/how-to-read-mms-data-in-android

I will add it to npm repo !

**Comment by briankabiro** [comment]
Awesome--best of luck on the new venture. 🚀

**Comment by briankabiro** [comment]
Going to close this for now
