### ISSUE TITLE
Crash App on device samsung

### ISSUE THREAD

**Issue by huuthinh245** [briankabiro/react-native-get-sms-android#68]
let filter = {
    box: 'all',
    minDate: date.valueOf(), // timestamp (in milliseconds since UNIX epoch)
    indexFrom: 0, // start from index 0
    maxCount: 500, // count of SMS to return each time
  };
I use like this. Maybe samsung doesn't support get all sms

**Comment by briankabiro** [comment]
Hi

Are you able to at least get back a message when using the package?

**Comment by huuthinh245** [comment]
> Hi
> 
> Are you able to at least get back a message when using the package?

yes sir
