### ISSUE TITLE
SmsAndroid undefined?

### ISSUE THREAD

**Issue by vincentaudebert** [briankabiro/react-native-get-sms-android#9]
Sorry I'm quite new to React Native.

I yarn installed your package and when I try this code
```
componentDidMount() {
        Sms.autoSend(
            '+111111111',
            'Test message',
            fail => {
                console.log('Failed with this error: ' + fail);
            },
            success => {
                console.log('SMS sent successfully');
            }
        );
    }
```

I get this error:
```
00:08:32: TypeError: undefined is not an object (evaluating '_reactNativeGetSmsAndroid2.default.autoSend')
```

Any idea of what I'm doing wrong?

**Comment by vincentaudebert** [comment]
Ah my bad... I'm using Expo... Could be the same error than this one: https://github.com/tkporter/react-native-sms/issues/25

**Comment by vincentaudebert** [comment]
Might be worth mentioning in the README that this package won't work if used with Expo?

**Comment by vincentaudebert** [comment]
@briankabiro I think it's Expo not supporting SMS access. I had found a github issue about it but I can't find it back.

**Comment by briankabiro** [comment]
I've updated the README accordingly.
